version: '3.9'

services:
  db:
    image: postgres
    container_name: product-api
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: productdb
    ports:
      - 5432:5432